-- Neutralised. This migration published messages, contracts and audit_log to
-- `supabase_realtime` to "match the feed client's three database-change
-- subscriptions". Those subscriptions never existed: there is not one
-- supabase.channel or postgres_changes call site in src/, and the feed client
-- has always polled an HTTP endpoint instead.
--
-- It is not merely unused. It cannot run against the live database, and the
-- proof is that it does not:
--
--   ERROR:  Realtime feed table public.messages must have RLS enabled
--   WARNING:  "wal_level" is insufficient to publish logical changes
--
-- The instance moved off Supabase to native Postgres (20260911190000). It has
-- no RLS enabled on any table and is not configured for logical replication, so
-- the RAISE EXCEPTION above aborts this file - and, because the migrations are
-- applied by hand in order (see CONTRIBUTING §1b), would abort every migration
-- after it on any fresh deployment of this shape. verify-e2e never caught that,
-- because its bootstrap creates the Supabase roles and the early migrations
-- enable RLS there, so the harness is the one environment where this works.
--
-- Left as a file rather than deleted so the history stays honest about what was
-- once intended here. The dashboard now gets change notifications from
-- a2a_pulse() over SSE, which is what the original comment was describing and
-- which has an actual subscriber.

SELECT 1 WHERE false;
